<a href="https://colab.research.google.com/github/simsia99/keras_deeplearning/blob/main/deep2-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
from tensorflow.keras.datasets import mnist
(train_images, train_labels), (test_images, test_labels)=mnist.load_data()

In [39]:
train_images.shape

(60000, 28, 28)

In [40]:
len(train_labels)

60000

In [41]:
train_labels

array([5, 0, 4, ..., 5, 6, 8], dtype=uint8)

In [42]:
test_images.shape

(10000, 28, 28)

In [43]:
len(test_labels)

10000

In [44]:
test_labels

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [45]:
from tensorflow import keras
from tensorflow.keras import layers

model=keras.Sequential([
    layers.Dense(512, activation="relu"),
    layers.Dense(10, activation="softmax")
])

In [63]:
model.compile(optimizer="rmsprop",
             loss="sparse_categorical_crossentropy",
             metrics=["accuracy"])

In [64]:
train_images=train_images.reshape((60000,28*28))
train_images=train_images.astype("float32")/255
test_images=test_images.reshape((10000,28*28))
test_images=test_images.astype("float32")/255

In [65]:
model.fit(train_images, train_labels, epochs=5, batch_size=128)

Epoch 1/5
469/469 [==============================] - 6s 10ms/step - loss: 2.3015 - accuracy: 0.1121
Epoch 2/5
469/469 [==============================] - 5s 10ms/step - loss: 2.3014 - accuracy: 0.1124
Epoch 3/5
469/469 [==============================] - 6s 12ms/step - loss: 2.3014 - accuracy: 0.1124
Epoch 4/5
469/469 [==============================] - 5s 10ms/step - loss: 2.3013 - accuracy: 0.1124
Epoch 5/5
469/469 [==============================] - 5s 12ms/step - loss: 2.3013 - accuracy: 0.1124


In [68]:
test_digits=test_images[0:10]
predictions=model.predict(test_digits)
predictions[0]

1/1 [==============================] - 0s 87ms/step


array([0.09854262, 0.11440717, 0.10085984, 0.10268975, 0.0971298 ,
       0.08787839, 0.09889752, 0.10444916, 0.09626964, 0.09887619],
      dtype=float32)

In [72]:
predictions[0].argmax()
predictions[0][7]
test_labels[0]

7

In [73]:
test_loss, test_acc = model.evaluate(test_images, test_labels)
print(f"테스트 정확도: {test_acc}")

313/313 [==============================] - 1s 3ms/step - loss: 2.3010 - accuracy: 0.1135
테스트 정확도: 0.11349999904632568


In [74]:
import numpy as np
x=np.array(12)
x

array(12)

In [75]:
x.ndim

0

In [76]:
x=np.array([12,3,6,14,7])
x

array([12,  3,  6, 14,  7])

In [77]:
x.ndim

1

In [79]:
x=np.array([[5,78,2,34,0],
           [6,79,3,35,1],
           [7,80,4,36,2]])
x.ndim

2